# Generated by Django 4.1.4 on 2023-01-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Take',
            new_name='Task',
        ),
    ]
